-- ════════════════════════════════════════════════
-- BSU Inventory Backup
-- Office ID : 1
-- Generated : 2026-07-25 15:25:25
-- ════════════════════════════════════════════════

SET FOREIGN_KEY_CHECKS = 0;
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

-- ── Table: `user_office_table` ──
DELETE FROM `user_office_table`;
INSERT INTO `user_office_table` (`user_office_id`, `user_office_name`) VALUES ('1', 'BAKERY') ON DUPLICATE KEY UPDATE `user_office_id` = VALUES(`user_office_id`), `user_office_name` = VALUES(`user_office_name`);
INSERT INTO `user_office_table` (`user_office_id`, `user_office_name`) VALUES ('2', 'FPC') ON DUPLICATE KEY UPDATE `user_office_id` = VALUES(`user_office_id`), `user_office_name` = VALUES(`user_office_name`);

-- ── Table: `level_of_access` ──
DELETE FROM `level_of_access`;
INSERT INTO `level_of_access` (`lvl_of_access_id`, `role`, `lvl_of_access`) VALUES ('1', 'Staff', '1') ON DUPLICATE KEY UPDATE `lvl_of_access_id` = VALUES(`lvl_of_access_id`), `role` = VALUES(`role`), `lvl_of_access` = VALUES(`lvl_of_access`);
INSERT INTO `level_of_access` (`lvl_of_access_id`, `role`, `lvl_of_access`) VALUES ('2', 'Custodian', '2') ON DUPLICATE KEY UPDATE `lvl_of_access_id` = VALUES(`lvl_of_access_id`), `role` = VALUES(`role`), `lvl_of_access` = VALUES(`lvl_of_access`);
INSERT INTO `level_of_access` (`lvl_of_access_id`, `role`, `lvl_of_access`) VALUES ('3', 'Manager', '3') ON DUPLICATE KEY UPDATE `lvl_of_access_id` = VALUES(`lvl_of_access_id`), `role` = VALUES(`role`), `lvl_of_access` = VALUES(`lvl_of_access`);
INSERT INTO `level_of_access` (`lvl_of_access_id`, `role`, `lvl_of_access`) VALUES ('4', 'Technical Staff', '4') ON DUPLICATE KEY UPDATE `lvl_of_access_id` = VALUES(`lvl_of_access_id`), `role` = VALUES(`role`), `lvl_of_access` = VALUES(`lvl_of_access`);

-- ── Table: `user_activity_table` ──
DELETE FROM `user_activity_table`;
INSERT INTO `user_activity_table` (`user_activity_id`, `user_activity`) VALUES ('1', 'Active') ON DUPLICATE KEY UPDATE `user_activity_id` = VALUES(`user_activity_id`), `user_activity` = VALUES(`user_activity`);
INSERT INTO `user_activity_table` (`user_activity_id`, `user_activity`) VALUES ('2', 'Deactivated') ON DUPLICATE KEY UPDATE `user_activity_id` = VALUES(`user_activity_id`), `user_activity` = VALUES(`user_activity`);
INSERT INTO `user_activity_table` (`user_activity_id`, `user_activity`) VALUES ('3', 'Pending') ON DUPLICATE KEY UPDATE `user_activity_id` = VALUES(`user_activity_id`), `user_activity` = VALUES(`user_activity`);

-- ── Table: `adjustment_reason` ──
DELETE FROM `adjustment_reason`;
INSERT INTO `adjustment_reason` (`adjustment_reason_id`, `adjustment_reason`) VALUES ('1', 'Correction') ON DUPLICATE KEY UPDATE `adjustment_reason_id` = VALUES(`adjustment_reason_id`), `adjustment_reason` = VALUES(`adjustment_reason`);
INSERT INTO `adjustment_reason` (`adjustment_reason_id`, `adjustment_reason`) VALUES ('2', 'Spoiled') ON DUPLICATE KEY UPDATE `adjustment_reason_id` = VALUES(`adjustment_reason_id`), `adjustment_reason` = VALUES(`adjustment_reason`);
INSERT INTO `adjustment_reason` (`adjustment_reason_id`, `adjustment_reason`) VALUES ('3', 'Damaged') ON DUPLICATE KEY UPDATE `adjustment_reason_id` = VALUES(`adjustment_reason_id`), `adjustment_reason` = VALUES(`adjustment_reason`);
INSERT INTO `adjustment_reason` (`adjustment_reason_id`, `adjustment_reason`) VALUES ('4', 'Lost') ON DUPLICATE KEY UPDATE `adjustment_reason_id` = VALUES(`adjustment_reason_id`), `adjustment_reason` = VALUES(`adjustment_reason`);
INSERT INTO `adjustment_reason` (`adjustment_reason_id`, `adjustment_reason`) VALUES ('5', 'Expired') ON DUPLICATE KEY UPDATE `adjustment_reason_id` = VALUES(`adjustment_reason_id`), `adjustment_reason` = VALUES(`adjustment_reason`);

-- ── Table: `transaction_type_table` ──
DELETE FROM `transaction_type_table`;
INSERT INTO `transaction_type_table` (`transaction_type_id`, `transaction_type`) VALUES ('1', 'receipt') ON DUPLICATE KEY UPDATE `transaction_type_id` = VALUES(`transaction_type_id`), `transaction_type` = VALUES(`transaction_type`);
INSERT INTO `transaction_type_table` (`transaction_type_id`, `transaction_type`) VALUES ('2', 'issue') ON DUPLICATE KEY UPDATE `transaction_type_id` = VALUES(`transaction_type_id`), `transaction_type` = VALUES(`transaction_type`);
INSERT INTO `transaction_type_table` (`transaction_type_id`, `transaction_type`) VALUES ('3', 'adjust_out') ON DUPLICATE KEY UPDATE `transaction_type_id` = VALUES(`transaction_type_id`), `transaction_type` = VALUES(`transaction_type`);

-- ── Table: `entity_table` ──
DELETE FROM `entity_table` WHERE `user_office_id` = 1;
INSERT INTO `entity_table` (`entity_id`, `entity`, `fund_cluster`, `user_office_id`) VALUES ('1', 'Benguet State University', '6', '1') ON DUPLICATE KEY UPDATE `entity_id` = VALUES(`entity_id`), `entity` = VALUES(`entity`), `fund_cluster` = VALUES(`fund_cluster`), `user_office_id` = VALUES(`user_office_id`);

-- ── Table: `unit_table` ──
DELETE FROM `unit_table` WHERE `user_office_id` = 1;
INSERT INTO `unit_table` (`unit_id`, `unit`, `user_office_id`) VALUES ('1', 'box', '1') ON DUPLICATE KEY UPDATE `unit_id` = VALUES(`unit_id`), `unit` = VALUES(`unit`), `user_office_id` = VALUES(`user_office_id`);
INSERT INTO `unit_table` (`unit_id`, `unit`, `user_office_id`) VALUES ('2', 'pack', '1') ON DUPLICATE KEY UPDATE `unit_id` = VALUES(`unit_id`), `unit` = VALUES(`unit`), `user_office_id` = VALUES(`user_office_id`);
INSERT INTO `unit_table` (`unit_id`, `unit`, `user_office_id`) VALUES ('3', 'bottle', '1') ON DUPLICATE KEY UPDATE `unit_id` = VALUES(`unit_id`), `unit` = VALUES(`unit`), `user_office_id` = VALUES(`user_office_id`);

-- ── Table: `type_of_product` ──
DELETE FROM `type_of_product` WHERE `user_office_id` = 1;
INSERT INTO `type_of_product` (`type_id`, `type`, `user_office_id`) VALUES ('1', 'Raw Product', '1') ON DUPLICATE KEY UPDATE `type_id` = VALUES(`type_id`), `type` = VALUES(`type`), `user_office_id` = VALUES(`user_office_id`);
INSERT INTO `type_of_product` (`type_id`, `type`, `user_office_id`) VALUES ('2', 'Janitorial Product', '1') ON DUPLICATE KEY UPDATE `type_id` = VALUES(`type_id`), `type` = VALUES(`type`), `user_office_id` = VALUES(`user_office_id`);
INSERT INTO `type_of_product` (`type_id`, `type`, `user_office_id`) VALUES ('3', 'Finished Product', '1') ON DUPLICATE KEY UPDATE `type_id` = VALUES(`type_id`), `type` = VALUES(`type`), `user_office_id` = VALUES(`user_office_id`);

-- ── Table: `reference_table` ──
DELETE FROM `reference_table` WHERE `user_office_id` = 1;
INSERT INTO `reference_table` (`reference_id`, `reference`, `user_office_id`) VALUES ('2', 'RCPC', '1') ON DUPLICATE KEY UPDATE `reference_id` = VALUES(`reference_id`), `reference` = VALUES(`reference`), `user_office_id` = VALUES(`user_office_id`);
INSERT INTO `reference_table` (`reference_id`, `reference`, `user_office_id`) VALUES ('3', '112323', '1') ON DUPLICATE KEY UPDATE `reference_id` = VALUES(`reference_id`), `reference` = VALUES(`reference`), `user_office_id` = VALUES(`user_office_id`);
INSERT INTO `reference_table` (`reference_id`, `reference`, `user_office_id`) VALUES ('4', 'sad', '1') ON DUPLICATE KEY UPDATE `reference_id` = VALUES(`reference_id`), `reference` = VALUES(`reference`), `user_office_id` = VALUES(`user_office_id`);
INSERT INTO `reference_table` (`reference_id`, `reference`, `user_office_id`) VALUES ('6', 'N/A', '1') ON DUPLICATE KEY UPDATE `reference_id` = VALUES(`reference_id`), `reference` = VALUES(`reference`), `user_office_id` = VALUES(`user_office_id`);

-- ── Table: `office_table` ──
DELETE FROM `office_table` WHERE `user_office_id` = 1;
INSERT INTO `office_table` (`office_id`, `office_name`, `user_office_id`) VALUES ('3', 'Marketing', '1') ON DUPLICATE KEY UPDATE `office_id` = VALUES(`office_id`), `office_name` = VALUES(`office_name`), `user_office_id` = VALUES(`user_office_id`);
INSERT INTO `office_table` (`office_id`, `office_name`, `user_office_id`) VALUES ('4', 'Coffee', '1') ON DUPLICATE KEY UPDATE `office_id` = VALUES(`office_id`), `office_name` = VALUES(`office_name`), `user_office_id` = VALUES(`user_office_id`);
INSERT INTO `office_table` (`office_id`, `office_name`, `user_office_id`) VALUES ('5', 'Marketing Office', '1') ON DUPLICATE KEY UPDATE `office_id` = VALUES(`office_id`), `office_name` = VALUES(`office_name`), `user_office_id` = VALUES(`user_office_id`);
INSERT INTO `office_table` (`office_id`, `office_name`, `user_office_id`) VALUES ('6', 'Bakery', '1') ON DUPLICATE KEY UPDATE `office_id` = VALUES(`office_id`), `office_name` = VALUES(`office_name`), `user_office_id` = VALUES(`user_office_id`);

-- ── Table: `user_table` ──
DELETE FROM `user_table` WHERE `user_office_id` = 1;
INSERT INTO `user_table` (`user_id`, `user_office_id`, `username`, `email`, `password`, `lvl_of_access_id`, `user_activity_id`) VALUES ('2', '1', 'manager', 'manager@gmail.com', '$2y$10$0hLP9cFk.vd9o8dotsfZ7.BbfAwyU2g/gw0VEmbLxC3SyakjDMZJO', '3', '1') ON DUPLICATE KEY UPDATE `user_id` = VALUES(`user_id`), `user_office_id` = VALUES(`user_office_id`), `username` = VALUES(`username`), `email` = VALUES(`email`), `password` = VALUES(`password`), `lvl_of_access_id` = VALUES(`lvl_of_access_id`), `user_activity_id` = VALUES(`user_activity_id`);
INSERT INTO `user_table` (`user_id`, `user_office_id`, `username`, `email`, `password`, `lvl_of_access_id`, `user_activity_id`) VALUES ('3', '1', 'staff', 'staff@gmail.com', '$2y$10$6hL81RnMpGvrqd.osoj5KuHWJaCDX.SJEgeRayx.LtzZVs4a2Z7E.', '1', '1') ON DUPLICATE KEY UPDATE `user_id` = VALUES(`user_id`), `user_office_id` = VALUES(`user_office_id`), `username` = VALUES(`username`), `email` = VALUES(`email`), `password` = VALUES(`password`), `lvl_of_access_id` = VALUES(`lvl_of_access_id`), `user_activity_id` = VALUES(`user_activity_id`);

-- ── Table: `product_table` ──
DELETE FROM `product_table` WHERE `user_office_id` = 1;
INSERT INTO `product_table` (`product_id`, `product_no`, `product`, `product_description`, `product_reorder_point`, `unit_id`, `type_id`, `user_office_id`, `entity_id`, `stock_no`) VALUES ('8', '1', 'Water', '12 ml', '10', '3', '3', '1', '1', 'BAKERY-0001') ON DUPLICATE KEY UPDATE `product_id` = VALUES(`product_id`), `product_no` = VALUES(`product_no`), `product` = VALUES(`product`), `product_description` = VALUES(`product_description`), `product_reorder_point` = VALUES(`product_reorder_point`), `unit_id` = VALUES(`unit_id`), `type_id` = VALUES(`type_id`), `user_office_id` = VALUES(`user_office_id`), `entity_id` = VALUES(`entity_id`), `stock_no` = VALUES(`stock_no`);
INSERT INTO `product_table` (`product_id`, `product_no`, `product`, `product_description`, `product_reorder_point`, `unit_id`, `type_id`, `user_office_id`, `entity_id`, `stock_no`) VALUES ('9', '2', 'C2', '12ml bottle boxed', '10', '1', '1', '1', '1', 'BAKERY-0002') ON DUPLICATE KEY UPDATE `product_id` = VALUES(`product_id`), `product_no` = VALUES(`product_no`), `product` = VALUES(`product`), `product_description` = VALUES(`product_description`), `product_reorder_point` = VALUES(`product_reorder_point`), `unit_id` = VALUES(`unit_id`), `type_id` = VALUES(`type_id`), `user_office_id` = VALUES(`user_office_id`), `entity_id` = VALUES(`entity_id`), `stock_no` = VALUES(`stock_no`);

-- ── Table: `batch_table` ──
DELETE FROM `batch_table` WHERE `user_office_id` = 1;
INSERT INTO `batch_table` (`batch_id`, `batch_no`, `barcode_value`, `product_id`, `expiration_date`, `user_office_id`, `reference_id`, `office_id`, `current_qty`, `date_received`, `created_at`, `updated_at`) VALUES ('19', 'B-BAKERY-20260718-0008', 'BC-000019-20260718-A531', '8', '2026-08-01', '1', NULL, NULL, '25', '2026-07-18', '2026-07-18 08:12:17', '2026-07-18 08:13:04') ON DUPLICATE KEY UPDATE `batch_id` = VALUES(`batch_id`), `batch_no` = VALUES(`batch_no`), `barcode_value` = VALUES(`barcode_value`), `product_id` = VALUES(`product_id`), `expiration_date` = VALUES(`expiration_date`), `user_office_id` = VALUES(`user_office_id`), `reference_id` = VALUES(`reference_id`), `office_id` = VALUES(`office_id`), `current_qty` = VALUES(`current_qty`), `date_received` = VALUES(`date_received`), `created_at` = VALUES(`created_at`), `updated_at` = VALUES(`updated_at`);
INSERT INTO `batch_table` (`batch_id`, `batch_no`, `barcode_value`, `product_id`, `expiration_date`, `user_office_id`, `reference_id`, `office_id`, `current_qty`, `date_received`, `created_at`, `updated_at`) VALUES ('20', 'B-BAKERY-20260721-0008', 'BC-000020-20260721-EED2', '8', '2026-07-31', '1', NULL, '3', '12', '2026-07-21', '2026-07-21 14:14:05', '2026-07-21 14:14:05') ON DUPLICATE KEY UPDATE `batch_id` = VALUES(`batch_id`), `batch_no` = VALUES(`batch_no`), `barcode_value` = VALUES(`barcode_value`), `product_id` = VALUES(`product_id`), `expiration_date` = VALUES(`expiration_date`), `user_office_id` = VALUES(`user_office_id`), `reference_id` = VALUES(`reference_id`), `office_id` = VALUES(`office_id`), `current_qty` = VALUES(`current_qty`), `date_received` = VALUES(`date_received`), `created_at` = VALUES(`created_at`), `updated_at` = VALUES(`updated_at`);
INSERT INTO `batch_table` (`batch_id`, `batch_no`, `barcode_value`, `product_id`, `expiration_date`, `user_office_id`, `reference_id`, `office_id`, `current_qty`, `date_received`, `created_at`, `updated_at`) VALUES ('21', 'B-BAKERY-20260721-0009', 'BC-000021-20260721-1B37', '9', '2026-07-31', '1', NULL, '3', '12', '2026-07-21', '2026-07-21 14:15:05', '2026-07-21 14:15:05') ON DUPLICATE KEY UPDATE `batch_id` = VALUES(`batch_id`), `batch_no` = VALUES(`batch_no`), `barcode_value` = VALUES(`barcode_value`), `product_id` = VALUES(`product_id`), `expiration_date` = VALUES(`expiration_date`), `user_office_id` = VALUES(`user_office_id`), `reference_id` = VALUES(`reference_id`), `office_id` = VALUES(`office_id`), `current_qty` = VALUES(`current_qty`), `date_received` = VALUES(`date_received`), `created_at` = VALUES(`created_at`), `updated_at` = VALUES(`updated_at`);
INSERT INTO `batch_table` (`batch_id`, `batch_no`, `barcode_value`, `product_id`, `expiration_date`, `user_office_id`, `reference_id`, `office_id`, `current_qty`, `date_received`, `created_at`, `updated_at`) VALUES ('22', 'B-BAKERY-20260721-0009', 'BC-000022-20260721-EDC4', '9', '2026-08-12', '1', NULL, NULL, '12', '2026-08-03', '2026-08-03 14:49:52', '2026-08-03 14:49:52') ON DUPLICATE KEY UPDATE `batch_id` = VALUES(`batch_id`), `batch_no` = VALUES(`batch_no`), `barcode_value` = VALUES(`barcode_value`), `product_id` = VALUES(`product_id`), `expiration_date` = VALUES(`expiration_date`), `user_office_id` = VALUES(`user_office_id`), `reference_id` = VALUES(`reference_id`), `office_id` = VALUES(`office_id`), `current_qty` = VALUES(`current_qty`), `date_received` = VALUES(`date_received`), `created_at` = VALUES(`created_at`), `updated_at` = VALUES(`updated_at`);

-- ── Table: `transaction_table` ──
DELETE FROM `transaction_table` WHERE `user_office_id` = 1;
INSERT INTO `transaction_table` (`transaction_id`, `transaction_type_id`, `transaction_qty`, `transaction_unit_cost`, `transaction_date`, `batch_id`, `reference_id`, `office_id`, `user_id`, `user_office_id`, `adjustment_reason_id`, `created_at`, `updated_at`) VALUES ('33', '1', '50', '120.00', '2026-07-18 08:12:17', '19', NULL, NULL, '2', '1', NULL, '2026-07-18 08:12:17', '2026-07-18 08:12:17') ON DUPLICATE KEY UPDATE `transaction_id` = VALUES(`transaction_id`), `transaction_type_id` = VALUES(`transaction_type_id`), `transaction_qty` = VALUES(`transaction_qty`), `transaction_unit_cost` = VALUES(`transaction_unit_cost`), `transaction_date` = VALUES(`transaction_date`), `batch_id` = VALUES(`batch_id`), `reference_id` = VALUES(`reference_id`), `office_id` = VALUES(`office_id`), `user_id` = VALUES(`user_id`), `user_office_id` = VALUES(`user_office_id`), `adjustment_reason_id` = VALUES(`adjustment_reason_id`), `created_at` = VALUES(`created_at`), `updated_at` = VALUES(`updated_at`);
INSERT INTO `transaction_table` (`transaction_id`, `transaction_type_id`, `transaction_qty`, `transaction_unit_cost`, `transaction_date`, `batch_id`, `reference_id`, `office_id`, `user_id`, `user_office_id`, `adjustment_reason_id`, `created_at`, `updated_at`) VALUES ('34', '2', '25', '130.00', '2026-07-18 08:13:04', '19', NULL, NULL, '2', '1', NULL, '2026-07-18 08:13:04', '2026-07-18 23:51:41') ON DUPLICATE KEY UPDATE `transaction_id` = VALUES(`transaction_id`), `transaction_type_id` = VALUES(`transaction_type_id`), `transaction_qty` = VALUES(`transaction_qty`), `transaction_unit_cost` = VALUES(`transaction_unit_cost`), `transaction_date` = VALUES(`transaction_date`), `batch_id` = VALUES(`batch_id`), `reference_id` = VALUES(`reference_id`), `office_id` = VALUES(`office_id`), `user_id` = VALUES(`user_id`), `user_office_id` = VALUES(`user_office_id`), `adjustment_reason_id` = VALUES(`adjustment_reason_id`), `created_at` = VALUES(`created_at`), `updated_at` = VALUES(`updated_at`);
INSERT INTO `transaction_table` (`transaction_id`, `transaction_type_id`, `transaction_qty`, `transaction_unit_cost`, `transaction_date`, `batch_id`, `reference_id`, `office_id`, `user_id`, `user_office_id`, `adjustment_reason_id`, `created_at`, `updated_at`) VALUES ('35', '1', '12', '120.00', '2026-07-21 14:14:05', '20', NULL, '3', '2', '1', NULL, '2026-07-21 14:14:05', '2026-07-21 14:14:05') ON DUPLICATE KEY UPDATE `transaction_id` = VALUES(`transaction_id`), `transaction_type_id` = VALUES(`transaction_type_id`), `transaction_qty` = VALUES(`transaction_qty`), `transaction_unit_cost` = VALUES(`transaction_unit_cost`), `transaction_date` = VALUES(`transaction_date`), `batch_id` = VALUES(`batch_id`), `reference_id` = VALUES(`reference_id`), `office_id` = VALUES(`office_id`), `user_id` = VALUES(`user_id`), `user_office_id` = VALUES(`user_office_id`), `adjustment_reason_id` = VALUES(`adjustment_reason_id`), `created_at` = VALUES(`created_at`), `updated_at` = VALUES(`updated_at`);
INSERT INTO `transaction_table` (`transaction_id`, `transaction_type_id`, `transaction_qty`, `transaction_unit_cost`, `transaction_date`, `batch_id`, `reference_id`, `office_id`, `user_id`, `user_office_id`, `adjustment_reason_id`, `created_at`, `updated_at`) VALUES ('36', '1', '12', '120.00', '2026-07-21 14:15:05', '21', NULL, '3', '2', '1', NULL, '2026-07-21 14:15:05', '2026-07-21 14:15:05') ON DUPLICATE KEY UPDATE `transaction_id` = VALUES(`transaction_id`), `transaction_type_id` = VALUES(`transaction_type_id`), `transaction_qty` = VALUES(`transaction_qty`), `transaction_unit_cost` = VALUES(`transaction_unit_cost`), `transaction_date` = VALUES(`transaction_date`), `batch_id` = VALUES(`batch_id`), `reference_id` = VALUES(`reference_id`), `office_id` = VALUES(`office_id`), `user_id` = VALUES(`user_id`), `user_office_id` = VALUES(`user_office_id`), `adjustment_reason_id` = VALUES(`adjustment_reason_id`), `created_at` = VALUES(`created_at`), `updated_at` = VALUES(`updated_at`);
INSERT INTO `transaction_table` (`transaction_id`, `transaction_type_id`, `transaction_qty`, `transaction_unit_cost`, `transaction_date`, `batch_id`, `reference_id`, `office_id`, `user_id`, `user_office_id`, `adjustment_reason_id`, `created_at`, `updated_at`) VALUES ('37', '1', '12', '120.00', '2026-08-03 14:49:52', '22', NULL, NULL, '2', '1', NULL, '2026-08-03 14:49:52', '2026-08-03 14:49:52') ON DUPLICATE KEY UPDATE `transaction_id` = VALUES(`transaction_id`), `transaction_type_id` = VALUES(`transaction_type_id`), `transaction_qty` = VALUES(`transaction_qty`), `transaction_unit_cost` = VALUES(`transaction_unit_cost`), `transaction_date` = VALUES(`transaction_date`), `batch_id` = VALUES(`batch_id`), `reference_id` = VALUES(`reference_id`), `office_id` = VALUES(`office_id`), `user_id` = VALUES(`user_id`), `user_office_id` = VALUES(`user_office_id`), `adjustment_reason_id` = VALUES(`adjustment_reason_id`), `created_at` = VALUES(`created_at`), `updated_at` = VALUES(`updated_at`);

-- ── Table: `temp_stockout` ──
DELETE FROM `temp_stockout` WHERE `user_office_id` = 1;
INSERT INTO `temp_stockout` (`temp_stockout_id`, `user_id`, `status`, `created_at`, `approved_by`, `approved_at`, `user_office_id`) VALUES ('1', '3', 'approved', '2026-07-12 15:00:41', '2', '2026-07-12 15:01:43', '1') ON DUPLICATE KEY UPDATE `temp_stockout_id` = VALUES(`temp_stockout_id`), `user_id` = VALUES(`user_id`), `status` = VALUES(`status`), `created_at` = VALUES(`created_at`), `approved_by` = VALUES(`approved_by`), `approved_at` = VALUES(`approved_at`), `user_office_id` = VALUES(`user_office_id`);
INSERT INTO `temp_stockout` (`temp_stockout_id`, `user_id`, `status`, `created_at`, `approved_by`, `approved_at`, `user_office_id`) VALUES ('2', '3', 'approved', '2026-07-12 15:01:15', '2', '2026-07-12 15:03:56', '1') ON DUPLICATE KEY UPDATE `temp_stockout_id` = VALUES(`temp_stockout_id`), `user_id` = VALUES(`user_id`), `status` = VALUES(`status`), `created_at` = VALUES(`created_at`), `approved_by` = VALUES(`approved_by`), `approved_at` = VALUES(`approved_at`), `user_office_id` = VALUES(`user_office_id`);
INSERT INTO `temp_stockout` (`temp_stockout_id`, `user_id`, `status`, `created_at`, `approved_by`, `approved_at`, `user_office_id`) VALUES ('3', '3', 'approved', '2026-07-12 15:03:44', '2', '2026-07-18 06:10:17', '1') ON DUPLICATE KEY UPDATE `temp_stockout_id` = VALUES(`temp_stockout_id`), `user_id` = VALUES(`user_id`), `status` = VALUES(`status`), `created_at` = VALUES(`created_at`), `approved_by` = VALUES(`approved_by`), `approved_at` = VALUES(`approved_at`), `user_office_id` = VALUES(`user_office_id`);
INSERT INTO `temp_stockout` (`temp_stockout_id`, `user_id`, `status`, `created_at`, `approved_by`, `approved_at`, `user_office_id`) VALUES ('4', '3', 'rejected', '2026-07-18 06:09:25', NULL, NULL, '1') ON DUPLICATE KEY UPDATE `temp_stockout_id` = VALUES(`temp_stockout_id`), `user_id` = VALUES(`user_id`), `status` = VALUES(`status`), `created_at` = VALUES(`created_at`), `approved_by` = VALUES(`approved_by`), `approved_at` = VALUES(`approved_at`), `user_office_id` = VALUES(`user_office_id`);
INSERT INTO `temp_stockout` (`temp_stockout_id`, `user_id`, `status`, `created_at`, `approved_by`, `approved_at`, `user_office_id`) VALUES ('5', '3', 'approved', '2026-07-18 07:37:35', '2', '2026-07-18 07:49:13', '1') ON DUPLICATE KEY UPDATE `temp_stockout_id` = VALUES(`temp_stockout_id`), `user_id` = VALUES(`user_id`), `status` = VALUES(`status`), `created_at` = VALUES(`created_at`), `approved_by` = VALUES(`approved_by`), `approved_at` = VALUES(`approved_at`), `user_office_id` = VALUES(`user_office_id`);
INSERT INTO `temp_stockout` (`temp_stockout_id`, `user_id`, `status`, `created_at`, `approved_by`, `approved_at`, `user_office_id`) VALUES ('6', '3', 'rejected', '2026-07-18 07:48:15', NULL, NULL, '1') ON DUPLICATE KEY UPDATE `temp_stockout_id` = VALUES(`temp_stockout_id`), `user_id` = VALUES(`user_id`), `status` = VALUES(`status`), `created_at` = VALUES(`created_at`), `approved_by` = VALUES(`approved_by`), `approved_at` = VALUES(`approved_at`), `user_office_id` = VALUES(`user_office_id`);
INSERT INTO `temp_stockout` (`temp_stockout_id`, `user_id`, `status`, `created_at`, `approved_by`, `approved_at`, `user_office_id`) VALUES ('7', '3', 'approved', '2026-07-18 07:50:04', '2', '2026-07-18 07:52:11', '1') ON DUPLICATE KEY UPDATE `temp_stockout_id` = VALUES(`temp_stockout_id`), `user_id` = VALUES(`user_id`), `status` = VALUES(`status`), `created_at` = VALUES(`created_at`), `approved_by` = VALUES(`approved_by`), `approved_at` = VALUES(`approved_at`), `user_office_id` = VALUES(`user_office_id`);
INSERT INTO `temp_stockout` (`temp_stockout_id`, `user_id`, `status`, `created_at`, `approved_by`, `approved_at`, `user_office_id`) VALUES ('8', '3', 'rejected', '2026-07-18 07:52:02', NULL, NULL, '1') ON DUPLICATE KEY UPDATE `temp_stockout_id` = VALUES(`temp_stockout_id`), `user_id` = VALUES(`user_id`), `status` = VALUES(`status`), `created_at` = VALUES(`created_at`), `approved_by` = VALUES(`approved_by`), `approved_at` = VALUES(`approved_at`), `user_office_id` = VALUES(`user_office_id`);
INSERT INTO `temp_stockout` (`temp_stockout_id`, `user_id`, `status`, `created_at`, `approved_by`, `approved_at`, `user_office_id`) VALUES ('9', '3', 'approved', '2026-07-18 07:57:11', '2', '2026-07-18 08:13:04', '1') ON DUPLICATE KEY UPDATE `temp_stockout_id` = VALUES(`temp_stockout_id`), `user_id` = VALUES(`user_id`), `status` = VALUES(`status`), `created_at` = VALUES(`created_at`), `approved_by` = VALUES(`approved_by`), `approved_at` = VALUES(`approved_at`), `user_office_id` = VALUES(`user_office_id`);
INSERT INTO `temp_stockout` (`temp_stockout_id`, `user_id`, `status`, `created_at`, `approved_by`, `approved_at`, `user_office_id`) VALUES ('10', '3', 'draft', '2026-07-18 08:12:50', NULL, NULL, '1') ON DUPLICATE KEY UPDATE `temp_stockout_id` = VALUES(`temp_stockout_id`), `user_id` = VALUES(`user_id`), `status` = VALUES(`status`), `created_at` = VALUES(`created_at`), `approved_by` = VALUES(`approved_by`), `approved_at` = VALUES(`approved_at`), `user_office_id` = VALUES(`user_office_id`);

-- ── Table: `temp_stockout_item` ──
DELETE FROM `temp_stockout_item` WHERE `user_office_id` = 1;
INSERT INTO `temp_stockout_item` (`temp_stockout_item_id`, `temp_stockout_id`, `product_id`, `quantity`, `unit`, `description`, `status`) VALUES ('10', '9', '8', '25', 'bottle', '12 ml', 'approved') ON DUPLICATE KEY UPDATE `temp_stockout_item_id` = VALUES(`temp_stockout_item_id`), `temp_stockout_id` = VALUES(`temp_stockout_id`), `product_id` = VALUES(`product_id`), `quantity` = VALUES(`quantity`), `unit` = VALUES(`unit`), `description` = VALUES(`description`), `status` = VALUES(`status`);


SET FOREIGN_KEY_CHECKS = 1;


-- ═══════════════════════════════════════
-- Backup appended: 20260725_152544
-- ═══════════════════════════════════════

-- ════════════════════════════════════════════════
-- BSU Inventory Backup
-- Office ID : 1
-- Generated : 2026-07-25 15:25:44
-- ════════════════════════════════════════════════

SET FOREIGN_KEY_CHECKS = 0;
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

-- ── Table: `user_office_table` ──
DELETE FROM `user_office_table`;
INSERT INTO `user_office_table` (`user_office_id`, `user_office_name`) VALUES ('1', 'BAKERY') ON DUPLICATE KEY UPDATE `user_office_id` = VALUES(`user_office_id`), `user_office_name` = VALUES(`user_office_name`);
INSERT INTO `user_office_table` (`user_office_id`, `user_office_name`) VALUES ('2', 'FPC') ON DUPLICATE KEY UPDATE `user_office_id` = VALUES(`user_office_id`), `user_office_name` = VALUES(`user_office_name`);

-- ── Table: `level_of_access` ──
DELETE FROM `level_of_access`;
INSERT INTO `level_of_access` (`lvl_of_access_id`, `role`, `lvl_of_access`) VALUES ('1', 'Staff', '1') ON DUPLICATE KEY UPDATE `lvl_of_access_id` = VALUES(`lvl_of_access_id`), `role` = VALUES(`role`), `lvl_of_access` = VALUES(`lvl_of_access`);
INSERT INTO `level_of_access` (`lvl_of_access_id`, `role`, `lvl_of_access`) VALUES ('2', 'Custodian', '2') ON DUPLICATE KEY UPDATE `lvl_of_access_id` = VALUES(`lvl_of_access_id`), `role` = VALUES(`role`), `lvl_of_access` = VALUES(`lvl_of_access`);
INSERT INTO `level_of_access` (`lvl_of_access_id`, `role`, `lvl_of_access`) VALUES ('3', 'Manager', '3') ON DUPLICATE KEY UPDATE `lvl_of_access_id` = VALUES(`lvl_of_access_id`), `role` = VALUES(`role`), `lvl_of_access` = VALUES(`lvl_of_access`);
INSERT INTO `level_of_access` (`lvl_of_access_id`, `role`, `lvl_of_access`) VALUES ('4', 'Technical Staff', '4') ON DUPLICATE KEY UPDATE `lvl_of_access_id` = VALUES(`lvl_of_access_id`), `role` = VALUES(`role`), `lvl_of_access` = VALUES(`lvl_of_access`);

-- ── Table: `user_activity_table` ──
DELETE FROM `user_activity_table`;
INSERT INTO `user_activity_table` (`user_activity_id`, `user_activity`) VALUES ('1', 'Active') ON DUPLICATE KEY UPDATE `user_activity_id` = VALUES(`user_activity_id`), `user_activity` = VALUES(`user_activity`);
INSERT INTO `user_activity_table` (`user_activity_id`, `user_activity`) VALUES ('2', 'Deactivated') ON DUPLICATE KEY UPDATE `user_activity_id` = VALUES(`user_activity_id`), `user_activity` = VALUES(`user_activity`);
INSERT INTO `user_activity_table` (`user_activity_id`, `user_activity`) VALUES ('3', 'Pending') ON DUPLICATE KEY UPDATE `user_activity_id` = VALUES(`user_activity_id`), `user_activity` = VALUES(`user_activity`);

-- ── Table: `adjustment_reason` ──
DELETE FROM `adjustment_reason`;
INSERT INTO `adjustment_reason` (`adjustment_reason_id`, `adjustment_reason`) VALUES ('1', 'Correction') ON DUPLICATE KEY UPDATE `adjustment_reason_id` = VALUES(`adjustment_reason_id`), `adjustment_reason` = VALUES(`adjustment_reason`);
INSERT INTO `adjustment_reason` (`adjustment_reason_id`, `adjustment_reason`) VALUES ('2', 'Spoiled') ON DUPLICATE KEY UPDATE `adjustment_reason_id` = VALUES(`adjustment_reason_id`), `adjustment_reason` = VALUES(`adjustment_reason`);
INSERT INTO `adjustment_reason` (`adjustment_reason_id`, `adjustment_reason`) VALUES ('3', 'Damaged') ON DUPLICATE KEY UPDATE `adjustment_reason_id` = VALUES(`adjustment_reason_id`), `adjustment_reason` = VALUES(`adjustment_reason`);
INSERT INTO `adjustment_reason` (`adjustment_reason_id`, `adjustment_reason`) VALUES ('4', 'Lost') ON DUPLICATE KEY UPDATE `adjustment_reason_id` = VALUES(`adjustment_reason_id`), `adjustment_reason` = VALUES(`adjustment_reason`);
INSERT INTO `adjustment_reason` (`adjustment_reason_id`, `adjustment_reason`) VALUES ('5', 'Expired') ON DUPLICATE KEY UPDATE `adjustment_reason_id` = VALUES(`adjustment_reason_id`), `adjustment_reason` = VALUES(`adjustment_reason`);

-- ── Table: `transaction_type_table` ──
DELETE FROM `transaction_type_table`;
INSERT INTO `transaction_type_table` (`transaction_type_id`, `transaction_type`) VALUES ('1', 'receipt') ON DUPLICATE KEY UPDATE `transaction_type_id` = VALUES(`transaction_type_id`), `transaction_type` = VALUES(`transaction_type`);
INSERT INTO `transaction_type_table` (`transaction_type_id`, `transaction_type`) VALUES ('2', 'issue') ON DUPLICATE KEY UPDATE `transaction_type_id` = VALUES(`transaction_type_id`), `transaction_type` = VALUES(`transaction_type`);
INSERT INTO `transaction_type_table` (`transaction_type_id`, `transaction_type`) VALUES ('3', 'adjust_out') ON DUPLICATE KEY UPDATE `transaction_type_id` = VALUES(`transaction_type_id`), `transaction_type` = VALUES(`transaction_type`);

-- ── Table: `entity_table` ──
DELETE FROM `entity_table` WHERE `user_office_id` = 1;
INSERT INTO `entity_table` (`entity_id`, `entity`, `fund_cluster`, `user_office_id`) VALUES ('1', 'Benguet State University', '6', '1') ON DUPLICATE KEY UPDATE `entity_id` = VALUES(`entity_id`), `entity` = VALUES(`entity`), `fund_cluster` = VALUES(`fund_cluster`), `user_office_id` = VALUES(`user_office_id`);

-- ── Table: `unit_table` ──
DELETE FROM `unit_table` WHERE `user_office_id` = 1;
INSERT INTO `unit_table` (`unit_id`, `unit`, `user_office_id`) VALUES ('1', 'box', '1') ON DUPLICATE KEY UPDATE `unit_id` = VALUES(`unit_id`), `unit` = VALUES(`unit`), `user_office_id` = VALUES(`user_office_id`);
INSERT INTO `unit_table` (`unit_id`, `unit`, `user_office_id`) VALUES ('2', 'pack', '1') ON DUPLICATE KEY UPDATE `unit_id` = VALUES(`unit_id`), `unit` = VALUES(`unit`), `user_office_id` = VALUES(`user_office_id`);
INSERT INTO `unit_table` (`unit_id`, `unit`, `user_office_id`) VALUES ('3', 'bottle', '1') ON DUPLICATE KEY UPDATE `unit_id` = VALUES(`unit_id`), `unit` = VALUES(`unit`), `user_office_id` = VALUES(`user_office_id`);

-- ── Table: `type_of_product` ──
DELETE FROM `type_of_product` WHERE `user_office_id` = 1;
INSERT INTO `type_of_product` (`type_id`, `type`, `user_office_id`) VALUES ('1', 'Raw Product', '1') ON DUPLICATE KEY UPDATE `type_id` = VALUES(`type_id`), `type` = VALUES(`type`), `user_office_id` = VALUES(`user_office_id`);
INSERT INTO `type_of_product` (`type_id`, `type`, `user_office_id`) VALUES ('2', 'Janitorial Product', '1') ON DUPLICATE KEY UPDATE `type_id` = VALUES(`type_id`), `type` = VALUES(`type`), `user_office_id` = VALUES(`user_office_id`);
INSERT INTO `type_of_product` (`type_id`, `type`, `user_office_id`) VALUES ('3', 'Finished Product', '1') ON DUPLICATE KEY UPDATE `type_id` = VALUES(`type_id`), `type` = VALUES(`type`), `user_office_id` = VALUES(`user_office_id`);

-- ── Table: `reference_table` ──
DELETE FROM `reference_table` WHERE `user_office_id` = 1;
INSERT INTO `reference_table` (`reference_id`, `reference`, `user_office_id`) VALUES ('2', 'RCPC', '1') ON DUPLICATE KEY UPDATE `reference_id` = VALUES(`reference_id`), `reference` = VALUES(`reference`), `user_office_id` = VALUES(`user_office_id`);
INSERT INTO `reference_table` (`reference_id`, `reference`, `user_office_id`) VALUES ('3', '112323', '1') ON DUPLICATE KEY UPDATE `reference_id` = VALUES(`reference_id`), `reference` = VALUES(`reference`), `user_office_id` = VALUES(`user_office_id`);
INSERT INTO `reference_table` (`reference_id`, `reference`, `user_office_id`) VALUES ('4', 'sad', '1') ON DUPLICATE KEY UPDATE `reference_id` = VALUES(`reference_id`), `reference` = VALUES(`reference`), `user_office_id` = VALUES(`user_office_id`);
INSERT INTO `reference_table` (`reference_id`, `reference`, `user_office_id`) VALUES ('6', 'N/A', '1') ON DUPLICATE KEY UPDATE `reference_id` = VALUES(`reference_id`), `reference` = VALUES(`reference`), `user_office_id` = VALUES(`user_office_id`);

-- ── Table: `office_table` ──
DELETE FROM `office_table` WHERE `user_office_id` = 1;
INSERT INTO `office_table` (`office_id`, `office_name`, `user_office_id`) VALUES ('3', 'Marketing', '1') ON DUPLICATE KEY UPDATE `office_id` = VALUES(`office_id`), `office_name` = VALUES(`office_name`), `user_office_id` = VALUES(`user_office_id`);
INSERT INTO `office_table` (`office_id`, `office_name`, `user_office_id`) VALUES ('4', 'Coffee', '1') ON DUPLICATE KEY UPDATE `office_id` = VALUES(`office_id`), `office_name` = VALUES(`office_name`), `user_office_id` = VALUES(`user_office_id`);
INSERT INTO `office_table` (`office_id`, `office_name`, `user_office_id`) VALUES ('5', 'Marketing Office', '1') ON DUPLICATE KEY UPDATE `office_id` = VALUES(`office_id`), `office_name` = VALUES(`office_name`), `user_office_id` = VALUES(`user_office_id`);
INSERT INTO `office_table` (`office_id`, `office_name`, `user_office_id`) VALUES ('6', 'Bakery', '1') ON DUPLICATE KEY UPDATE `office_id` = VALUES(`office_id`), `office_name` = VALUES(`office_name`), `user_office_id` = VALUES(`user_office_id`);

-- ── Table: `user_table` ──
DELETE FROM `user_table` WHERE `user_office_id` = 1;
INSERT INTO `user_table` (`user_id`, `user_office_id`, `username`, `email`, `password`, `lvl_of_access_id`, `user_activity_id`) VALUES ('2', '1', 'manager', 'manager@gmail.com', '$2y$10$0hLP9cFk.vd9o8dotsfZ7.BbfAwyU2g/gw0VEmbLxC3SyakjDMZJO', '3', '1') ON DUPLICATE KEY UPDATE `user_id` = VALUES(`user_id`), `user_office_id` = VALUES(`user_office_id`), `username` = VALUES(`username`), `email` = VALUES(`email`), `password` = VALUES(`password`), `lvl_of_access_id` = VALUES(`lvl_of_access_id`), `user_activity_id` = VALUES(`user_activity_id`);
INSERT INTO `user_table` (`user_id`, `user_office_id`, `username`, `email`, `password`, `lvl_of_access_id`, `user_activity_id`) VALUES ('3', '1', 'staff', 'staff@gmail.com', '$2y$10$6hL81RnMpGvrqd.osoj5KuHWJaCDX.SJEgeRayx.LtzZVs4a2Z7E.', '1', '1') ON DUPLICATE KEY UPDATE `user_id` = VALUES(`user_id`), `user_office_id` = VALUES(`user_office_id`), `username` = VALUES(`username`), `email` = VALUES(`email`), `password` = VALUES(`password`), `lvl_of_access_id` = VALUES(`lvl_of_access_id`), `user_activity_id` = VALUES(`user_activity_id`);

-- ── Table: `product_table` ──
DELETE FROM `product_table` WHERE `user_office_id` = 1;
INSERT INTO `product_table` (`product_id`, `product_no`, `product`, `product_description`, `product_reorder_point`, `unit_id`, `type_id`, `user_office_id`, `entity_id`, `stock_no`) VALUES ('8', '1', 'Water', '12 ml', '10', '3', '3', '1', '1', 'BAKERY-0001') ON DUPLICATE KEY UPDATE `product_id` = VALUES(`product_id`), `product_no` = VALUES(`product_no`), `product` = VALUES(`product`), `product_description` = VALUES(`product_description`), `product_reorder_point` = VALUES(`product_reorder_point`), `unit_id` = VALUES(`unit_id`), `type_id` = VALUES(`type_id`), `user_office_id` = VALUES(`user_office_id`), `entity_id` = VALUES(`entity_id`), `stock_no` = VALUES(`stock_no`);
INSERT INTO `product_table` (`product_id`, `product_no`, `product`, `product_description`, `product_reorder_point`, `unit_id`, `type_id`, `user_office_id`, `entity_id`, `stock_no`) VALUES ('9', '2', 'C2', '12ml bottle boxed', '10', '1', '1', '1', '1', 'BAKERY-0002') ON DUPLICATE KEY UPDATE `product_id` = VALUES(`product_id`), `product_no` = VALUES(`product_no`), `product` = VALUES(`product`), `product_description` = VALUES(`product_description`), `product_reorder_point` = VALUES(`product_reorder_point`), `unit_id` = VALUES(`unit_id`), `type_id` = VALUES(`type_id`), `user_office_id` = VALUES(`user_office_id`), `entity_id` = VALUES(`entity_id`), `stock_no` = VALUES(`stock_no`);

-- ── Table: `batch_table` ──
DELETE FROM `batch_table` WHERE `user_office_id` = 1;
INSERT INTO `batch_table` (`batch_id`, `batch_no`, `barcode_value`, `product_id`, `expiration_date`, `user_office_id`, `reference_id`, `office_id`, `current_qty`, `date_received`, `created_at`, `updated_at`) VALUES ('19', 'B-BAKERY-20260718-0008', 'BC-000019-20260718-A531', '8', '2026-08-01', '1', NULL, NULL, '25', '2026-07-18', '2026-07-18 08:12:17', '2026-07-18 08:13:04') ON DUPLICATE KEY UPDATE `batch_id` = VALUES(`batch_id`), `batch_no` = VALUES(`batch_no`), `barcode_value` = VALUES(`barcode_value`), `product_id` = VALUES(`product_id`), `expiration_date` = VALUES(`expiration_date`), `user_office_id` = VALUES(`user_office_id`), `reference_id` = VALUES(`reference_id`), `office_id` = VALUES(`office_id`), `current_qty` = VALUES(`current_qty`), `date_received` = VALUES(`date_received`), `created_at` = VALUES(`created_at`), `updated_at` = VALUES(`updated_at`);
INSERT INTO `batch_table` (`batch_id`, `batch_no`, `barcode_value`, `product_id`, `expiration_date`, `user_office_id`, `reference_id`, `office_id`, `current_qty`, `date_received`, `created_at`, `updated_at`) VALUES ('20', 'B-BAKERY-20260721-0008', 'BC-000020-20260721-EED2', '8', '2026-07-31', '1', NULL, '3', '12', '2026-07-21', '2026-07-21 14:14:05', '2026-07-21 14:14:05') ON DUPLICATE KEY UPDATE `batch_id` = VALUES(`batch_id`), `batch_no` = VALUES(`batch_no`), `barcode_value` = VALUES(`barcode_value`), `product_id` = VALUES(`product_id`), `expiration_date` = VALUES(`expiration_date`), `user_office_id` = VALUES(`user_office_id`), `reference_id` = VALUES(`reference_id`), `office_id` = VALUES(`office_id`), `current_qty` = VALUES(`current_qty`), `date_received` = VALUES(`date_received`), `created_at` = VALUES(`created_at`), `updated_at` = VALUES(`updated_at`);
INSERT INTO `batch_table` (`batch_id`, `batch_no`, `barcode_value`, `product_id`, `expiration_date`, `user_office_id`, `reference_id`, `office_id`, `current_qty`, `date_received`, `created_at`, `updated_at`) VALUES ('21', 'B-BAKERY-20260721-0009', 'BC-000021-20260721-1B37', '9', '2026-07-31', '1', NULL, '3', '12', '2026-07-21', '2026-07-21 14:15:05', '2026-07-21 14:15:05') ON DUPLICATE KEY UPDATE `batch_id` = VALUES(`batch_id`), `batch_no` = VALUES(`batch_no`), `barcode_value` = VALUES(`barcode_value`), `product_id` = VALUES(`product_id`), `expiration_date` = VALUES(`expiration_date`), `user_office_id` = VALUES(`user_office_id`), `reference_id` = VALUES(`reference_id`), `office_id` = VALUES(`office_id`), `current_qty` = VALUES(`current_qty`), `date_received` = VALUES(`date_received`), `created_at` = VALUES(`created_at`), `updated_at` = VALUES(`updated_at`);
INSERT INTO `batch_table` (`batch_id`, `batch_no`, `barcode_value`, `product_id`, `expiration_date`, `user_office_id`, `reference_id`, `office_id`, `current_qty`, `date_received`, `created_at`, `updated_at`) VALUES ('22', 'B-BAKERY-20260721-0009', 'BC-000022-20260721-EDC4', '9', '2026-08-12', '1', NULL, NULL, '12', '2026-08-03', '2026-08-03 14:49:52', '2026-08-03 14:49:52') ON DUPLICATE KEY UPDATE `batch_id` = VALUES(`batch_id`), `batch_no` = VALUES(`batch_no`), `barcode_value` = VALUES(`barcode_value`), `product_id` = VALUES(`product_id`), `expiration_date` = VALUES(`expiration_date`), `user_office_id` = VALUES(`user_office_id`), `reference_id` = VALUES(`reference_id`), `office_id` = VALUES(`office_id`), `current_qty` = VALUES(`current_qty`), `date_received` = VALUES(`date_received`), `created_at` = VALUES(`created_at`), `updated_at` = VALUES(`updated_at`);

-- ── Table: `transaction_table` ──
DELETE FROM `transaction_table` WHERE `user_office_id` = 1;
INSERT INTO `transaction_table` (`transaction_id`, `transaction_type_id`, `transaction_qty`, `transaction_unit_cost`, `transaction_date`, `batch_id`, `reference_id`, `office_id`, `user_id`, `user_office_id`, `adjustment_reason_id`, `created_at`, `updated_at`) VALUES ('33', '1', '50', '120.00', '2026-07-18 08:12:17', '19', NULL, NULL, '2', '1', NULL, '2026-07-18 08:12:17', '2026-07-18 08:12:17') ON DUPLICATE KEY UPDATE `transaction_id` = VALUES(`transaction_id`), `transaction_type_id` = VALUES(`transaction_type_id`), `transaction_qty` = VALUES(`transaction_qty`), `transaction_unit_cost` = VALUES(`transaction_unit_cost`), `transaction_date` = VALUES(`transaction_date`), `batch_id` = VALUES(`batch_id`), `reference_id` = VALUES(`reference_id`), `office_id` = VALUES(`office_id`), `user_id` = VALUES(`user_id`), `user_office_id` = VALUES(`user_office_id`), `adjustment_reason_id` = VALUES(`adjustment_reason_id`), `created_at` = VALUES(`created_at`), `updated_at` = VALUES(`updated_at`);
INSERT INTO `transaction_table` (`transaction_id`, `transaction_type_id`, `transaction_qty`, `transaction_unit_cost`, `transaction_date`, `batch_id`, `reference_id`, `office_id`, `user_id`, `user_office_id`, `adjustment_reason_id`, `created_at`, `updated_at`) VALUES ('34', '2', '25', '130.00', '2026-07-18 08:13:04', '19', NULL, NULL, '2', '1', NULL, '2026-07-18 08:13:04', '2026-07-18 23:51:41') ON DUPLICATE KEY UPDATE `transaction_id` = VALUES(`transaction_id`), `transaction_type_id` = VALUES(`transaction_type_id`), `transaction_qty` = VALUES(`transaction_qty`), `transaction_unit_cost` = VALUES(`transaction_unit_cost`), `transaction_date` = VALUES(`transaction_date`), `batch_id` = VALUES(`batch_id`), `reference_id` = VALUES(`reference_id`), `office_id` = VALUES(`office_id`), `user_id` = VALUES(`user_id`), `user_office_id` = VALUES(`user_office_id`), `adjustment_reason_id` = VALUES(`adjustment_reason_id`), `created_at` = VALUES(`created_at`), `updated_at` = VALUES(`updated_at`);
INSERT INTO `transaction_table` (`transaction_id`, `transaction_type_id`, `transaction_qty`, `transaction_unit_cost`, `transaction_date`, `batch_id`, `reference_id`, `office_id`, `user_id`, `user_office_id`, `adjustment_reason_id`, `created_at`, `updated_at`) VALUES ('35', '1', '12', '120.00', '2026-07-21 14:14:05', '20', NULL, '3', '2', '1', NULL, '2026-07-21 14:14:05', '2026-07-21 14:14:05') ON DUPLICATE KEY UPDATE `transaction_id` = VALUES(`transaction_id`), `transaction_type_id` = VALUES(`transaction_type_id`), `transaction_qty` = VALUES(`transaction_qty`), `transaction_unit_cost` = VALUES(`transaction_unit_cost`), `transaction_date` = VALUES(`transaction_date`), `batch_id` = VALUES(`batch_id`), `reference_id` = VALUES(`reference_id`), `office_id` = VALUES(`office_id`), `user_id` = VALUES(`user_id`), `user_office_id` = VALUES(`user_office_id`), `adjustment_reason_id` = VALUES(`adjustment_reason_id`), `created_at` = VALUES(`created_at`), `updated_at` = VALUES(`updated_at`);
INSERT INTO `transaction_table` (`transaction_id`, `transaction_type_id`, `transaction_qty`, `transaction_unit_cost`, `transaction_date`, `batch_id`, `reference_id`, `office_id`, `user_id`, `user_office_id`, `adjustment_reason_id`, `created_at`, `updated_at`) VALUES ('36', '1', '12', '120.00', '2026-07-21 14:15:05', '21', NULL, '3', '2', '1', NULL, '2026-07-21 14:15:05', '2026-07-21 14:15:05') ON DUPLICATE KEY UPDATE `transaction_id` = VALUES(`transaction_id`), `transaction_type_id` = VALUES(`transaction_type_id`), `transaction_qty` = VALUES(`transaction_qty`), `transaction_unit_cost` = VALUES(`transaction_unit_cost`), `transaction_date` = VALUES(`transaction_date`), `batch_id` = VALUES(`batch_id`), `reference_id` = VALUES(`reference_id`), `office_id` = VALUES(`office_id`), `user_id` = VALUES(`user_id`), `user_office_id` = VALUES(`user_office_id`), `adjustment_reason_id` = VALUES(`adjustment_reason_id`), `created_at` = VALUES(`created_at`), `updated_at` = VALUES(`updated_at`);
INSERT INTO `transaction_table` (`transaction_id`, `transaction_type_id`, `transaction_qty`, `transaction_unit_cost`, `transaction_date`, `batch_id`, `reference_id`, `office_id`, `user_id`, `user_office_id`, `adjustment_reason_id`, `created_at`, `updated_at`) VALUES ('37', '1', '12', '120.00', '2026-08-03 14:49:52', '22', NULL, NULL, '2', '1', NULL, '2026-08-03 14:49:52', '2026-08-03 14:49:52') ON DUPLICATE KEY UPDATE `transaction_id` = VALUES(`transaction_id`), `transaction_type_id` = VALUES(`transaction_type_id`), `transaction_qty` = VALUES(`transaction_qty`), `transaction_unit_cost` = VALUES(`transaction_unit_cost`), `transaction_date` = VALUES(`transaction_date`), `batch_id` = VALUES(`batch_id`), `reference_id` = VALUES(`reference_id`), `office_id` = VALUES(`office_id`), `user_id` = VALUES(`user_id`), `user_office_id` = VALUES(`user_office_id`), `adjustment_reason_id` = VALUES(`adjustment_reason_id`), `created_at` = VALUES(`created_at`), `updated_at` = VALUES(`updated_at`);

-- ── Table: `temp_stockout` ──
DELETE FROM `temp_stockout` WHERE `user_office_id` = 1;
INSERT INTO `temp_stockout` (`temp_stockout_id`, `user_id`, `status`, `created_at`, `approved_by`, `approved_at`, `user_office_id`) VALUES ('1', '3', 'approved', '2026-07-12 15:00:41', '2', '2026-07-12 15:01:43', '1') ON DUPLICATE KEY UPDATE `temp_stockout_id` = VALUES(`temp_stockout_id`), `user_id` = VALUES(`user_id`), `status` = VALUES(`status`), `created_at` = VALUES(`created_at`), `approved_by` = VALUES(`approved_by`), `approved_at` = VALUES(`approved_at`), `user_office_id` = VALUES(`user_office_id`);
INSERT INTO `temp_stockout` (`temp_stockout_id`, `user_id`, `status`, `created_at`, `approved_by`, `approved_at`, `user_office_id`) VALUES ('2', '3', 'approved', '2026-07-12 15:01:15', '2', '2026-07-12 15:03:56', '1') ON DUPLICATE KEY UPDATE `temp_stockout_id` = VALUES(`temp_stockout_id`), `user_id` = VALUES(`user_id`), `status` = VALUES(`status`), `created_at` = VALUES(`created_at`), `approved_by` = VALUES(`approved_by`), `approved_at` = VALUES(`approved_at`), `user_office_id` = VALUES(`user_office_id`);
INSERT INTO `temp_stockout` (`temp_stockout_id`, `user_id`, `status`, `created_at`, `approved_by`, `approved_at`, `user_office_id`) VALUES ('3', '3', 'approved', '2026-07-12 15:03:44', '2', '2026-07-18 06:10:17', '1') ON DUPLICATE KEY UPDATE `temp_stockout_id` = VALUES(`temp_stockout_id`), `user_id` = VALUES(`user_id`), `status` = VALUES(`status`), `created_at` = VALUES(`created_at`), `approved_by` = VALUES(`approved_by`), `approved_at` = VALUES(`approved_at`), `user_office_id` = VALUES(`user_office_id`);
INSERT INTO `temp_stockout` (`temp_stockout_id`, `user_id`, `status`, `created_at`, `approved_by`, `approved_at`, `user_office_id`) VALUES ('4', '3', 'rejected', '2026-07-18 06:09:25', NULL, NULL, '1') ON DUPLICATE KEY UPDATE `temp_stockout_id` = VALUES(`temp_stockout_id`), `user_id` = VALUES(`user_id`), `status` = VALUES(`status`), `created_at` = VALUES(`created_at`), `approved_by` = VALUES(`approved_by`), `approved_at` = VALUES(`approved_at`), `user_office_id` = VALUES(`user_office_id`);
INSERT INTO `temp_stockout` (`temp_stockout_id`, `user_id`, `status`, `created_at`, `approved_by`, `approved_at`, `user_office_id`) VALUES ('5', '3', 'approved', '2026-07-18 07:37:35', '2', '2026-07-18 07:49:13', '1') ON DUPLICATE KEY UPDATE `temp_stockout_id` = VALUES(`temp_stockout_id`), `user_id` = VALUES(`user_id`), `status` = VALUES(`status`), `created_at` = VALUES(`created_at`), `approved_by` = VALUES(`approved_by`), `approved_at` = VALUES(`approved_at`), `user_office_id` = VALUES(`user_office_id`);
INSERT INTO `temp_stockout` (`temp_stockout_id`, `user_id`, `status`, `created_at`, `approved_by`, `approved_at`, `user_office_id`) VALUES ('6', '3', 'rejected', '2026-07-18 07:48:15', NULL, NULL, '1') ON DUPLICATE KEY UPDATE `temp_stockout_id` = VALUES(`temp_stockout_id`), `user_id` = VALUES(`user_id`), `status` = VALUES(`status`), `created_at` = VALUES(`created_at`), `approved_by` = VALUES(`approved_by`), `approved_at` = VALUES(`approved_at`), `user_office_id` = VALUES(`user_office_id`);
INSERT INTO `temp_stockout` (`temp_stockout_id`, `user_id`, `status`, `created_at`, `approved_by`, `approved_at`, `user_office_id`) VALUES ('7', '3', 'approved', '2026-07-18 07:50:04', '2', '2026-07-18 07:52:11', '1') ON DUPLICATE KEY UPDATE `temp_stockout_id` = VALUES(`temp_stockout_id`), `user_id` = VALUES(`user_id`), `status` = VALUES(`status`), `created_at` = VALUES(`created_at`), `approved_by` = VALUES(`approved_by`), `approved_at` = VALUES(`approved_at`), `user_office_id` = VALUES(`user_office_id`);
INSERT INTO `temp_stockout` (`temp_stockout_id`, `user_id`, `status`, `created_at`, `approved_by`, `approved_at`, `user_office_id`) VALUES ('8', '3', 'rejected', '2026-07-18 07:52:02', NULL, NULL, '1') ON DUPLICATE KEY UPDATE `temp_stockout_id` = VALUES(`temp_stockout_id`), `user_id` = VALUES(`user_id`), `status` = VALUES(`status`), `created_at` = VALUES(`created_at`), `approved_by` = VALUES(`approved_by`), `approved_at` = VALUES(`approved_at`), `user_office_id` = VALUES(`user_office_id`);
INSERT INTO `temp_stockout` (`temp_stockout_id`, `user_id`, `status`, `created_at`, `approved_by`, `approved_at`, `user_office_id`) VALUES ('9', '3', 'approved', '2026-07-18 07:57:11', '2', '2026-07-18 08:13:04', '1') ON DUPLICATE KEY UPDATE `temp_stockout_id` = VALUES(`temp_stockout_id`), `user_id` = VALUES(`user_id`), `status` = VALUES(`status`), `created_at` = VALUES(`created_at`), `approved_by` = VALUES(`approved_by`), `approved_at` = VALUES(`approved_at`), `user_office_id` = VALUES(`user_office_id`);
INSERT INTO `temp_stockout` (`temp_stockout_id`, `user_id`, `status`, `created_at`, `approved_by`, `approved_at`, `user_office_id`) VALUES ('10', '3', 'draft', '2026-07-18 08:12:50', NULL, NULL, '1') ON DUPLICATE KEY UPDATE `temp_stockout_id` = VALUES(`temp_stockout_id`), `user_id` = VALUES(`user_id`), `status` = VALUES(`status`), `created_at` = VALUES(`created_at`), `approved_by` = VALUES(`approved_by`), `approved_at` = VALUES(`approved_at`), `user_office_id` = VALUES(`user_office_id`);

-- ── Table: `temp_stockout_item` ──
DELETE FROM `temp_stockout_item` WHERE `user_office_id` = 1;
INSERT INTO `temp_stockout_item` (`temp_stockout_item_id`, `temp_stockout_id`, `product_id`, `quantity`, `unit`, `description`, `status`) VALUES ('10', '9', '8', '25', 'bottle', '12 ml', 'approved') ON DUPLICATE KEY UPDATE `temp_stockout_item_id` = VALUES(`temp_stockout_item_id`), `temp_stockout_id` = VALUES(`temp_stockout_id`), `product_id` = VALUES(`product_id`), `quantity` = VALUES(`quantity`), `unit` = VALUES(`unit`), `description` = VALUES(`description`), `status` = VALUES(`status`);


SET FOREIGN_KEY_CHECKS = 1;
